version: "3.5"

services:

  https-portal:
    image: steveltn/https-portal:1
    environment:
      CLIENT_MAX_BODY_SIZE: 1024M
      DOMAINS: >
        moodle.test -> http://moodle:8080,
      STAGE: local
    volumes:
      - https-portal_certs:/var/lib/https-portal
      - https-portal_logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - moodle

  moodle:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_PASSWORD=12345Abcde
    expose:
      - 8080
    volumes:
      - moodle:/bitnami/moodle
      - moodledata:/bitnami/moodledata
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: 12345Abcde
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  https-portal_certs:
  https-portal_logs:
  moodle:
  moodledata:
  mariadb:
